Repository networkx/nx-parallel, pull requests merged in 2024-09, with the labels that each got.

#83 Test on Python 3.13-dev
  .github/workflows/test.yml
Labels: type: Maintenance, Sprints

#80 Chore/style cleanup utility functions
  .pre-commit-config.yaml
  _nx_parallel/update_get_info.py
  nx_parallel/interface.py
  nx_parallel/tests/test_get_chunks.py
  nx_parallel/utils/chunk.py
  nx_parallel/utils/decorators.py
  nx_parallel/utils/tests/__init__.py
  nx_parallel/utils/tests/test_chunk.py
Labels: type: Maintenance

#85 Adding ruff as a developer dependency
  pyproject.toml
Labels: type: Bug fix

#84 Clean up and bump deps, ruff, pre-commit
  .github/workflows/release.yml
  .gitignore
  .pre-commit-config.yaml
  _nx_parallel/__init__.py
  nx_parallel/algorithms/approximation/connectivity.py
  nx_parallel/algorithms/efficiency_measures.py
  pyproject.toml
Labels: type: Maintenance
