Repository networkx/nx-parallel, pull requests merged in 2024-06, with the labels that each got.

#63 Revisiting nxp algorithms
  .github/workflows/test.yml
  .gitignore
  CONTRIBUTING.md
  README.md
  _nx_parallel/__init__.py
  _nx_parallel/update_get_info.py
  assets/images/backend_box_ss.png
  nx_parallel/algorithms/approximation/connectivity.py
  nx_parallel/algorithms/bipartite/redundancy.py
  nx_parallel/algorithms/centrality/betweenness.py
  nx_parallel/algorithms/cluster.py
  nx_parallel/algorithms/connectivity/connectivity.py
  nx_parallel/algorithms/efficiency_measures.py
  nx_parallel/algorithms/isolate.py
  nx_parallel/algorithms/shortest_paths/generic.py
  nx_parallel/algorithms/shortest_paths/unweighted.py
  nx_parallel/algorithms/shortest_paths/weighted.py
  nx_parallel/algorithms/tournament.py
  nx_parallel/algorithms/vitality.py
  nx_parallel/interface.py
  nx_parallel/tests/__init__.py
  nx_parallel/tests/test_get_chunks.py
  pyproject.toml
  timing/heatmap_is_reachable_timing.png
  timing/heatmap_is_strongly_connected_timing.png
  timing/timing_individual_function.py
Labels: type: Maintenance

#60 Add parallel version of edge_betweenness_centrality
  README.md
  _nx_parallel/__init__.py
  benchmarks/benchmarks/bench_centrality.py
  nx_parallel/algorithms/centrality/betweenness.py
  nx_parallel/interface.py
  nx_parallel/tests/test_get_chunks.py
Labels: type: Enhancement

#70 DOC: minor doc_string changes to check write access
  _nx_parallel/update_get_info.py
  nx_parallel/tests/test_get_chunks.py
Labels: type: Documentation

#69 MAINT: Switching to setuptools
  pyproject.toml
Labels: type: Maintenance
